name: First workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps: 
      - name:
        run: 
            echo "hola chico"
            echo "Done - hast
  deploy: 
    runs-on: ubuntu-latest
    steps:
      - name: Build project
        run: npm run build
      - name: Deploy
        run: echo "deploying"
