name: First workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps: 
      - name: print holla
        run: 
          echo "hola chico"
          echo "Done - hasta la vista!"
